# -*- mode: ruby -*-
# vi: set ft=ruby :

# Requires Vagrant 1.5+

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :private_network, ip: "192.168.77.10"

  # Set Vagrant VM name (by default it is called 'default')
  config.vm.define :sfis_sinatra do |t|
  end
  
  # Provision via bootstrap shell script
  config.vm.provision :shell, :path => "bootstrap.sh"

end